on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v8
      with:
        dry_run: true
    - name: Upload Site
      uses: actions/upload-pages-artifact@v3
    - name: Publish Site
      uses: actions/deploy-pages@v4
